# Generated by Django 3.0.7 on 2020-06-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('run_date', models.DateTimeField(auto_now_add=True, verbose_name='date submitted')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
