# Generated by Django 3.0.8 on 2020-07-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_filesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesubmission',
            name='md5_hash',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='filesubmission',
            name='yaraResult',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='filesubmission',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='filesubmission',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
