# Generated by Django 3.0.8 on 2020-07-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_auto_20200707_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesubmission',
            name='md5_hash',
        ),
        migrations.AddField(
            model_name='filesubmission',
            name='VTDetections',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='filesubmission',
            name='VTUrl',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='filesubmission',
            name='sha256_hash',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
